# Generated by Django 6.1.1 on 2026-09-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('food', 'Restaurants & Food'), ('shopping', 'Shopping & Retail'), ('electronics', 'Electronics & Computers'), ('home', 'Home & Living'), ('beauty', 'Health & Beauty'), ('transport', 'Transport & Logistics'), ('education', 'Education & Training'), ('services', 'Business Services'), ('sports', 'Sports & Recreation'), ('pets', 'Pets & Animals'), ('travel', 'Travel & Tourism'), ('other', 'Other Services')], max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
