# Generated by Django 6.1.1 on 2026-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('received', 'Package Received'), ('transit', 'In Transit'), ('delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='received', max_length=20),
        ),
    ]
