# Generated by Django 6.1.1 on 2026-09-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_package_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Package Received'), ('transit', 'In Transit'), ('delivery', 'Out for Delivery'), ('delivered', 'Delivered')], max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
