# Generated by Django 6.1.1 on 2026-09-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trackingupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
