# Generated by Django 6.1.1 on 2026-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_package_latitude_package_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='destination_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='destination_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
