# Generated by Django 6.1.1 on 2026-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_package_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingupdate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingupdate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
